IF OBJECT_ID('dbo.SKU','U') IS NOT NULL DROP TABLE dbo.SKU;
CREATE TABLE dbo.SKU (
ID INT IDENTITY (1,1), 
Code AS 's' + CAST(ID as varchar(10)) UNIQUE, 
Name NVARCHAR(50)
CONSTRAINT PK_SKU PRIMARY KEY(ID));

IF OBJECT_ID('dbo.Family','U') IS NOT NULL DROP TABLE dbo.Family;
CREATE TABLE dbo.Family (
ID  INT IDENTITY,
SurName NVARCHAR(50), 
BudgetValue DECIMAL(18,2)
CONSTRAINT PK_Family PRIMARY KEY(ID));

IF OBJECT_ID('dbo.Basket','U') IS NOT NULL DROP TABLE dbo.Basket;
CREATE TABLE dbo.Basket (
ID INT IDENTITY NOT NULL, 
ID_SKU INT,
ID_Family INT,
Quantity DECIMAL(18,2),
Value DECIMAL(18,2),
PurchaseDate DATETIME DEFAULT SYSDATETIME(),
DiscountValue DECIMAL(18,2),
CONSTRAINT PK_Basket PRIMARY KEY(ID),
CONSTRAINT FK1_Basket FOREIGN KEY(ID_SKU) REFERENCES dbo.SKU(ID) ON DELETE CASCADE,
CONSTRAINT FK2_Basket FOREIGN KEY(ID_Family) REFERENCES dbo.Family(ID) ON DELETE CASCADE,
CONSTRAINT CHK_Basket CHECK (Quantity >= 0 AND Value >= 0));